version: "3"

tasks:
  build:
    desc: Build gallery site from project root
    cmds:
      - hugo --gc --minify -e production

  css:
    depends: [build]
    desc: Compile production CSS using PostCSS to `assets/css/compiled/main.css`
    cmds:
      - npm run build:css

  dev:
    desc: Start development server for Hextra theme
    cmds:
      - npm run dev:theme
